openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Check server status
      responses:
        '200':
          description: Server working fine
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /shorten:
    post:
      summary: Create short URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      shortUrl:
                        type: string
                      longUrl:
                        type: string
        '400':
          description: URL is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /{id}:
    get:
      summary: Redirect to long URL
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to long URL
        '400':
          description: ID required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Short URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
