openapi: 3.0.0
info:
  title: URL Shortener API
  version: 1.0.0
paths:
  /:
    get:
      summary: Checks if the server is working fine.
      responses:
        '200':
          description: Server status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /shorten:
    post:
      summary: Creates a shortened URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        '201':
          description: Short URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      shortUrl:
                        type: string
                      longUrl:
                        type: string
        '400':
          description: URL is required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /{id}:
    get:
      summary: Retrieves the original URL using the shortened URL id.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirects to the original URL
        '400':
          description: ID required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Short URL not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components: {}
